# h/t https://github.com/jonchang/homebrew-tap/blob/main/.github/workflows/bump.yml
name: bump n bottle

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: current version & new version space separated
        required: false

concurrency:
  group: bump/${{ github.event.inputs.version || 'livecheck' }}
  cancel-in-progress: true

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: pkgxdev/setup@v2

      - run: .github/actions/bump.ts ${{ github.event.inputs.version }}
        id: bump
        env:
          TAP: pkgxdev/made

      - name: git push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - uses: softprops/action-gh-release@v1
        with:
          name: ${{steps.bump.outputs.name}} v${{ steps.bump.outputs.version }}
          tag_name: v${{ steps.bump.outputs.version }}
          files: bottles/*
          fail_on_unmatched_files: true
          generate_release_notes: true
        if: steps.bump.outputs.name

  test:
    needs: bump
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - name: brew install pkgxdev/made/pkgx
        run: |
          brew install pkgxdev/made/pkgx
          pkgx semverator satisfies ^1 1.0.0
