name: ci/bumper

on:
  pull_request:
    paths:
      - .github/actions/bump.ts
      - .github/workflows/ci.bump.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pkgxdev/setup@v3

      - run: git checkout 591bbfc206850d6be45976fce9682d99c8179927 -- ./pkg[xm].rb
      - run: .github/actions/bump.ts pkgx 2.1.1 2.1.2
      - run: .github/actions/bump.ts pkgm 0.3.0 0.3.1

      - uses: actions/upload-artifact@v4
        with:
          path: '*.rb'
          name: formulae

      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install ./pkgm.rb
