name: ci/pkgx

on:
  pull_request:
    paths:
      - pkgx.rb

jobs:
  smoke:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install --build-from-source ./pkgx.rb
      - run: brew test pkgx
      - run: brew audit pkgx
